### ISSUE TITLE
Не выкидывается исключение вида IllegalArgumentException в консоли когда минимальный баланс больше максимального

### ISSUE THREAD

**Issue by Yana-Gus** [Veronika-Kulieva/javaqa-team-diplom-2#12]
# Описание
Если мин. баланс больше максимального, должно выкидываться исключение вида IllegalArgumentException с сообщением в консоли "Минимальный баланс не может быть больше максимального, а у вас: "
# Локация дефекта
https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/a54854a2b7d225bf223fc8b1baa9f92fc04c2899/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать объект SavingAccount с параметрами: initialBalance 2000, minBalance 11_000, maxBalance 10_000, rate 5
3. Запустить программу
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Должно выкидываться исключение вида IllegalArgumentException с сообщением в консоли "Минимальный баланс не может быть больше максимального, а у вас: "
*Фактический результат:* В консоли выводится сообщение об ошибке: "Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown."
# Тест
https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/d4b5e9d6caf6b68960087291d9e63f57f6500e17/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9
# Скриншот
![image](https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/assets/126955638/886b02df-4522-4a5a-96d7-9c761b5c853d)

# Окружение
* **Операционная система:** Windows 8.1
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Veronika-Kulieva** [comment]
Баг исправлен
