### ISSUE TITLE
Не должен меняться баланс счета, если баланс после покупки равен минимальному балансу

### ISSUE THREAD

**Issue by Yana-Gus** [Veronika-Kulieva/javaqa-team-diplom-2#16]
# Описание
Если баланс после покупки равен минимальному, то операция должна быть отклонена, баланс не должен измениться.
# Локация дефекта
https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/d4b5e9d6caf6b68960087291d9e63f57f6500e17/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L51-L52
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Вызвать метод "pay" с параметрами: initialBalance 2000, minBalance 1_000, maxBalance 10_000, rate 5 и amount 1_000
3. Запустить программу
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс: 2_000
*Фактический результат:* Баланс: 1000
# Тест
https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/d4b5e9d6caf6b68960087291d9e63f57f6500e17/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L72
# Скриншот
![image](https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/assets/126955638/a82f74c8-5f4b-4261-a169-529c312f9900)
# Окружение
* **Операционная система:** Windows 8.1
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Veronika-Kulieva** [comment]
Баг исправлен
