### ISSUE TITLE
Баланс становиться равным сумме пополнения после пополнения карты на указанную сумму

### ISSUE THREAD

**Issue by Yana-Gus** [Veronika-Kulieva/javaqa-team-diplom-2#17]
# Описание
Если баланс после пополнения меньше максимального баланса, то баланс должен увеличиться на сумму пополнения.
# Локация дефекта
https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/d4b5e9d6caf6b68960087291d9e63f57f6500e17/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73-L74
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Вызвать метод "add" с параметрами: initialBalance 2000, minBalance 1_000, maxBalance 10_000, rate 5 и amount 7_000
3. Запустить программу
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс: 9000
*Фактический результат:* Баланс: 7000
# Тест
https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/blob/d4b5e9d6caf6b68960087291d9e63f57f6500e17/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L100
# Скриншот
![image](https://github.com/Veronika-Kulieva/javaqa-team-diplom-2/assets/126955638/2b89ef7c-28f4-4e20-9857-e4e6580571a5)
# Окружение
* **Операционная система:** Windows 8.1
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Veronika-Kulieva** [comment]
Баг исправлен
